//==============================================================================
// Copyright (c) 2015-2023 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for DX11 GFX6 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_DX11_GFX6
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_DX11_GFX6

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for DX11Gfx6 Public counter index
#define GPUTIME_PUBLIC_DX11_GFX6 0
#define GPUBUSY_PUBLIC_DX11_GFX6 1
#define TESSELLATORBUSY_PUBLIC_DX11_GFX6 2
#define VSBUSY_PUBLIC_DX11_GFX6 3
#define VSTIME_PUBLIC_DX11_GFX6 4
#define HSBUSY_PUBLIC_DX11_GFX6 5
#define HSTIME_PUBLIC_DX11_GFX6 6
#define DSBUSY_PUBLIC_DX11_GFX6 7
#define DSTIME_PUBLIC_DX11_GFX6 8
#define GSBUSY_PUBLIC_DX11_GFX6 9
#define GSTIME_PUBLIC_DX11_GFX6 10
#define PSBUSY_PUBLIC_DX11_GFX6 11
#define PSTIME_PUBLIC_DX11_GFX6 12
#define CSBUSY_PUBLIC_DX11_GFX6 13
#define CSTIME_PUBLIC_DX11_GFX6 14
#define VSVERTICESIN_PUBLIC_DX11_GFX6 15
#define HSPATCHES_PUBLIC_DX11_GFX6 16
#define DSVERTICESIN_PUBLIC_DX11_GFX6 17
#define GSPRIMSIN_PUBLIC_DX11_GFX6 18
#define GSVERTICESOUT_PUBLIC_DX11_GFX6 19
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_DX11_GFX6 20
#define PRIMITIVESIN_PUBLIC_DX11_GFX6 21
#define CULLEDPRIMS_PUBLIC_DX11_GFX6 22
#define CLIPPEDPRIMS_PUBLIC_DX11_GFX6 23
#define PASTALLEDONRASTERIZER_PUBLIC_DX11_GFX6 24
#define PSPIXELSOUT_PUBLIC_DX11_GFX6 25
#define PSEXPORTSTALLS_PUBLIC_DX11_GFX6 26
#define CSTHREADGROUPS_PUBLIC_DX11_GFX6 27
#define CSWAVEFRONTS_PUBLIC_DX11_GFX6 28
#define CSTHREADS_PUBLIC_DX11_GFX6 29
#define CSVALUINSTS_PUBLIC_DX11_GFX6 30
#define CSVALUUTILIZATION_PUBLIC_DX11_GFX6 31
#define CSSALUINSTS_PUBLIC_DX11_GFX6 32
#define CSVFETCHINSTS_PUBLIC_DX11_GFX6 33
#define CSSFETCHINSTS_PUBLIC_DX11_GFX6 34
#define CSVWRITEINSTS_PUBLIC_DX11_GFX6 35
#define CSVALUBUSY_PUBLIC_DX11_GFX6 36
#define CSSALUBUSY_PUBLIC_DX11_GFX6 37
#define CSMEMUNITBUSY_PUBLIC_DX11_GFX6 38
#define CSMEMUNITSTALLED_PUBLIC_DX11_GFX6 39
#define CSFETCHSIZE_PUBLIC_DX11_GFX6 40
#define CSWRITESIZE_PUBLIC_DX11_GFX6 41
#define CSCACHEHIT_PUBLIC_DX11_GFX6 42
#define CSWRITEUNITSTALLED_PUBLIC_DX11_GFX6 43
#define CSGDSINSTS_PUBLIC_DX11_GFX6 44
#define CSLDSINSTS_PUBLIC_DX11_GFX6 45
#define CSALUSTALLEDBYLDS_PUBLIC_DX11_GFX6 46
#define CSLDSBANKCONFLICT_PUBLIC_DX11_GFX6 47
#define TEXUNITBUSY_PUBLIC_DX11_GFX6 48
#define TEXTRIFILTERINGPCT_PUBLIC_DX11_GFX6 49
#define TEXVOLFILTERINGPCT_PUBLIC_DX11_GFX6 50
#define TEXAVEANISOTROPY_PUBLIC_DX11_GFX6 51
#define DEPTHSTENCILTESTBUSY_PUBLIC_DX11_GFX6 52
#define HIZTILESACCEPTED_PUBLIC_DX11_GFX6 53
#define PREZTILESDETAILCULLED_PUBLIC_DX11_GFX6 54
#define HIZQUADSCULLED_PUBLIC_DX11_GFX6 55
#define PREZQUADSCULLED_PUBLIC_DX11_GFX6 56
#define POSTZQUADS_PUBLIC_DX11_GFX6 57
#define PREZSAMPLESPASSING_PUBLIC_DX11_GFX6 58
#define PREZSAMPLESFAILINGS_PUBLIC_DX11_GFX6 59
#define PREZSAMPLESFAILINGZ_PUBLIC_DX11_GFX6 60
#define POSTZSAMPLESPASSING_PUBLIC_DX11_GFX6 61
#define POSTZSAMPLESFAILINGS_PUBLIC_DX11_GFX6 62
#define POSTZSAMPLESFAILINGZ_PUBLIC_DX11_GFX6 63
#define ZUNITSTALLED_PUBLIC_DX11_GFX6 64
#define DBMEMREAD_PUBLIC_DX11_GFX6 65
#define DBMEMWRITTEN_PUBLIC_DX11_GFX6 66
#define CBMEMREAD_PUBLIC_DX11_GFX6 67
#define CBMEMWRITTEN_PUBLIC_DX11_GFX6 68
#define CBSLOWPIXELPCT_PUBLIC_DX11_GFX6 69

/// Number of public counters for DX11 GFX6 
const size_t kDx11Gfx6PublicCounterCount = 70;

/// Array of public counters for DX11 GFX6 
extern const GpaCounterDesc kDx11Gfx6PublicCounters[kDx11Gfx6PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_DX11_GFX6
