//==============================================================================
// Copyright (c) 2015-2023 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief PublicCounterDefinitions for OGLP GFX7 for testing.
//==============================================================================

// *** Note, this is an auto-generated file. Do not edit. Execute PublicCounterCompiler to rebuild.

#ifndef GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX7
#define GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX7

#include "gpu_perf_api_unit_tests/counters/gpa_counter_desc.h"

/// Macros for OGLPGfx7 Public counter index
#define GPUTIME_PUBLIC_OGLP_GFX7 0
#define GPUBUSY_PUBLIC_OGLP_GFX7 1
#define GPUBUSYCYCLES_PUBLIC_OGLP_GFX7 2
#define TESSELLATORBUSY_PUBLIC_OGLP_GFX7 3
#define TESSELLATORBUSYCYCLES_PUBLIC_OGLP_GFX7 4
#define VSBUSY_PUBLIC_OGLP_GFX7 5
#define VSBUSYCYCLES_PUBLIC_OGLP_GFX7 6
#define VSTIME_PUBLIC_OGLP_GFX7 7
#define HSBUSY_PUBLIC_OGLP_GFX7 8
#define HSBUSYCYCLES_PUBLIC_OGLP_GFX7 9
#define HSTIME_PUBLIC_OGLP_GFX7 10
#define DSBUSY_PUBLIC_OGLP_GFX7 11
#define DSBUSYCYCLES_PUBLIC_OGLP_GFX7 12
#define DSTIME_PUBLIC_OGLP_GFX7 13
#define GSBUSY_PUBLIC_OGLP_GFX7 14
#define GSBUSYCYCLES_PUBLIC_OGLP_GFX7 15
#define GSTIME_PUBLIC_OGLP_GFX7 16
#define PSBUSY_PUBLIC_OGLP_GFX7 17
#define PSBUSYCYCLES_PUBLIC_OGLP_GFX7 18
#define PSTIME_PUBLIC_OGLP_GFX7 19
#define CSBUSY_PUBLIC_OGLP_GFX7 20
#define CSBUSYCYCLES_PUBLIC_OGLP_GFX7 21
#define CSTIME_PUBLIC_OGLP_GFX7 22
#define VSVERTICESIN_PUBLIC_OGLP_GFX7 23
#define VSVALUINSTCOUNT_PUBLIC_OGLP_GFX7 24
#define VSSALUINSTCOUNT_PUBLIC_OGLP_GFX7 25
#define VSVALUBUSY_PUBLIC_OGLP_GFX7 26
#define VSVALUBUSYCYCLES_PUBLIC_OGLP_GFX7 27
#define VSSALUBUSY_PUBLIC_OGLP_GFX7 28
#define VSSALUBUSYCYCLES_PUBLIC_OGLP_GFX7 29
#define HSPATCHES_PUBLIC_OGLP_GFX7 30
#define HSVALUINSTCOUNT_PUBLIC_OGLP_GFX7 31
#define HSSALUINSTCOUNT_PUBLIC_OGLP_GFX7 32
#define HSVALUBUSY_PUBLIC_OGLP_GFX7 33
#define HSVALUBUSYCYCLES_PUBLIC_OGLP_GFX7 34
#define HSSALUBUSY_PUBLIC_OGLP_GFX7 35
#define HSSALUBUSYCYCLES_PUBLIC_OGLP_GFX7 36
#define DSVERTICESIN_PUBLIC_OGLP_GFX7 37
#define DSVALUINSTCOUNT_PUBLIC_OGLP_GFX7 38
#define DSSALUINSTCOUNT_PUBLIC_OGLP_GFX7 39
#define DSVALUBUSY_PUBLIC_OGLP_GFX7 40
#define DSVALUBUSYCYCLES_PUBLIC_OGLP_GFX7 41
#define DSSALUBUSY_PUBLIC_OGLP_GFX7 42
#define DSSALUBUSYCYCLES_PUBLIC_OGLP_GFX7 43
#define GSPRIMSIN_PUBLIC_OGLP_GFX7 44
#define GSVERTICESOUT_PUBLIC_OGLP_GFX7 45
#define GSVALUINSTCOUNT_PUBLIC_OGLP_GFX7 46
#define GSSALUINSTCOUNT_PUBLIC_OGLP_GFX7 47
#define GSVALUBUSY_PUBLIC_OGLP_GFX7 48
#define GSVALUBUSYCYCLES_PUBLIC_OGLP_GFX7 49
#define GSSALUBUSY_PUBLIC_OGLP_GFX7 50
#define GSSALUBUSYCYCLES_PUBLIC_OGLP_GFX7 51
#define PRIMITIVEASSEMBLYBUSY_PUBLIC_OGLP_GFX7 52
#define PRIMITIVEASSEMBLYBUSYCYCLES_PUBLIC_OGLP_GFX7 53
#define PRIMITIVESIN_PUBLIC_OGLP_GFX7 54
#define CULLEDPRIMS_PUBLIC_OGLP_GFX7 55
#define CLIPPEDPRIMS_PUBLIC_OGLP_GFX7 56
#define PASTALLEDONRASTERIZER_PUBLIC_OGLP_GFX7 57
#define PASTALLEDONRASTERIZERCYCLES_PUBLIC_OGLP_GFX7 58
#define PSPIXELSOUT_PUBLIC_OGLP_GFX7 59
#define PSEXPORTSTALLS_PUBLIC_OGLP_GFX7 60
#define PSEXPORTSTALLSCYCLES_PUBLIC_OGLP_GFX7 61
#define PSVALUINSTCOUNT_PUBLIC_OGLP_GFX7 62
#define PSSALUINSTCOUNT_PUBLIC_OGLP_GFX7 63
#define PSVALUBUSY_PUBLIC_OGLP_GFX7 64
#define PSVALUBUSYCYCLES_PUBLIC_OGLP_GFX7 65
#define PSSALUBUSY_PUBLIC_OGLP_GFX7 66
#define PSSALUBUSYCYCLES_PUBLIC_OGLP_GFX7 67
#define CSTHREADGROUPS_PUBLIC_OGLP_GFX7 68
#define CSWAVEFRONTS_PUBLIC_OGLP_GFX7 69
#define CSTHREADS_PUBLIC_OGLP_GFX7 70
#define CSVALUINSTS_PUBLIC_OGLP_GFX7 71
#define CSVALUUTILIZATION_PUBLIC_OGLP_GFX7 72
#define CSSALUINSTS_PUBLIC_OGLP_GFX7 73
#define CSVFETCHINSTS_PUBLIC_OGLP_GFX7 74
#define CSSFETCHINSTS_PUBLIC_OGLP_GFX7 75
#define CSVWRITEINSTS_PUBLIC_OGLP_GFX7 76
#define CSFLATVMEMINSTS_PUBLIC_OGLP_GFX7 77
#define CSVALUBUSY_PUBLIC_OGLP_GFX7 78
#define CSVALUBUSYCYCLES_PUBLIC_OGLP_GFX7 79
#define CSSALUBUSY_PUBLIC_OGLP_GFX7 80
#define CSSALUBUSYCYCLES_PUBLIC_OGLP_GFX7 81
#define CSMEMUNITBUSY_PUBLIC_OGLP_GFX7 82
#define CSMEMUNITBUSYCYCLES_PUBLIC_OGLP_GFX7 83
#define CSMEMUNITSTALLED_PUBLIC_OGLP_GFX7 84
#define CSMEMUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX7 85
#define CSFETCHSIZE_PUBLIC_OGLP_GFX7 86
#define CSWRITESIZE_PUBLIC_OGLP_GFX7 87
#define CSCACHEHIT_PUBLIC_OGLP_GFX7 88
#define CSCACHEHITCOUNT_PUBLIC_OGLP_GFX7 89
#define CSCACHEMISSCOUNT_PUBLIC_OGLP_GFX7 90
#define CSWRITEUNITSTALLED_PUBLIC_OGLP_GFX7 91
#define CSWRITEUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX7 92
#define CSGDSINSTS_PUBLIC_OGLP_GFX7 93
#define CSLDSINSTS_PUBLIC_OGLP_GFX7 94
#define CSFLATLDSINSTS_PUBLIC_OGLP_GFX7 95
#define CSALUSTALLEDBYLDS_PUBLIC_OGLP_GFX7 96
#define CSALUSTALLEDBYLDSCYCLES_PUBLIC_OGLP_GFX7 97
#define CSLDSBANKCONFLICT_PUBLIC_OGLP_GFX7 98
#define CSLDSBANKCONFLICTCYCLES_PUBLIC_OGLP_GFX7 99
#define TEXUNITBUSY_PUBLIC_OGLP_GFX7 100
#define TEXUNITBUSYCYCLES_PUBLIC_OGLP_GFX7 101
#define TEXTRIFILTERINGPCT_PUBLIC_OGLP_GFX7 102
#define TEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX7 103
#define NOTEXTRIFILTERINGCOUNT_PUBLIC_OGLP_GFX7 104
#define TEXVOLFILTERINGPCT_PUBLIC_OGLP_GFX7 105
#define TEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX7 106
#define NOTEXVOLFILTERINGCOUNT_PUBLIC_OGLP_GFX7 107
#define TEXAVEANISOTROPY_PUBLIC_OGLP_GFX7 108
#define DEPTHSTENCILTESTBUSY_PUBLIC_OGLP_GFX7 109
#define DEPTHSTENCILTESTBUSYCOUNT_PUBLIC_OGLP_GFX7 110
#define HIZTILESACCEPTED_PUBLIC_OGLP_GFX7 111
#define HIZTILESACCEPTEDCOUNT_PUBLIC_OGLP_GFX7 112
#define HIZTILESREJECTEDCOUNT_PUBLIC_OGLP_GFX7 113
#define PREZTILESDETAILCULLED_PUBLIC_OGLP_GFX7 114
#define PREZTILESDETAILCULLEDCOUNT_PUBLIC_OGLP_GFX7 115
#define PREZTILESDETAILSURVIVINGCOUNT_PUBLIC_OGLP_GFX7 116
#define HIZQUADSCULLED_PUBLIC_OGLP_GFX7 117
#define HIZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX7 118
#define HIZQUADSACCEPTEDCOUNT_PUBLIC_OGLP_GFX7 119
#define PREZQUADSCULLED_PUBLIC_OGLP_GFX7 120
#define PREZQUADSCULLEDCOUNT_PUBLIC_OGLP_GFX7 121
#define PREZQUADSSURVIVINGCOUNT_PUBLIC_OGLP_GFX7 122
#define POSTZQUADS_PUBLIC_OGLP_GFX7 123
#define POSTZQUADCOUNT_PUBLIC_OGLP_GFX7 124
#define PREZSAMPLESPASSING_PUBLIC_OGLP_GFX7 125
#define PREZSAMPLESFAILINGS_PUBLIC_OGLP_GFX7 126
#define PREZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX7 127
#define POSTZSAMPLESPASSING_PUBLIC_OGLP_GFX7 128
#define POSTZSAMPLESFAILINGS_PUBLIC_OGLP_GFX7 129
#define POSTZSAMPLESFAILINGZ_PUBLIC_OGLP_GFX7 130
#define ZUNITSTALLED_PUBLIC_OGLP_GFX7 131
#define ZUNITSTALLEDCYCLES_PUBLIC_OGLP_GFX7 132
#define DBMEMREAD_PUBLIC_OGLP_GFX7 133
#define DBMEMWRITTEN_PUBLIC_OGLP_GFX7 134
#define CBMEMREAD_PUBLIC_OGLP_GFX7 135
#define CBMEMWRITTEN_PUBLIC_OGLP_GFX7 136
#define CBSLOWPIXELPCT_PUBLIC_OGLP_GFX7 137
#define CBSLOWPIXELCOUNT_PUBLIC_OGLP_GFX7 138

/// Number of public counters for OGLP GFX7 
const size_t kOglpGfx7PublicCounterCount = 139;

/// Array of public counters for OGLP GFX7 
extern const GpaCounterDesc kOglpGfx7PublicCounters[kOglpGfx7PublicCounterCount];

#endif  // GPA_AUTO_GEN_UNIT_TESTS_COUNTERS_PUBLIC_OGLP_GFX7
