//==============================================================================
// Copyright (c) 2010-2023 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief GL counter definitions for GFX7.
//==============================================================================

// This file is NOT autogenerated by the ConvertHWEnums project.

#ifndef GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GL_GFX7_H_
#define GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GL_GFX7_H_

// clang-format off

#include <set>

struct GpaHardwareCounterDesc;
struct GpaCounterGroupDesc;
struct GpaSqCounterGroupDesc;

namespace counter_gl_gfx7
{
    extern std::vector<std::vector<GpaHardwareCounterDesc>*> kGlCounterGroupArrayGfx7;                     ///< Array of hardware counter groups for Gl for Gfx7 family
    extern std::vector<GpaCounterGroupDesc>                  kHwGlGroupsGfx7;                              ///< Array of counter groups for Gl for Gfx7 family
    extern GpaCounterGroupExposedCounterDesc                 kHwGlExposedCountersByGroupGfx7[];            ///< Array of exposed counter groups for Gl for Gfx7 family
    extern GpaPaddedCounterDesc                              kGlPaddedCounterByGroupGfx7[];                ///< Array of reserved counter for Gl for Gfx7 family
    extern GpaSqCounterGroupDesc                             kHwGlSqGroupsGfx7[];                          ///< Array of SQ groups for Gl for Gfx7 family
    extern unsigned int                                      kHwGlSqIsolatedGroupsGfx7[];                  ///< Array of counter groups isolated from SQ counter groups for Gl for Gfx7 family
    extern const unsigned int                                kHwGlGpuTimeBottomToBottomDurationIndexGfx7;  ///< Index of delta between the previous command reaching bottom of pipe and the current command reaching bottom of pipe, will not include latency of first data to travel through pipeline, best for large data sets. for Gl for Gfx7 family
    extern const unsigned int                                kHwGlGpuTimeBottomToBottomStartIndexGfx7;     ///< Index of time of the previous command reaching bottom of pipe for Gl for Gfx7 family
    extern const unsigned int                                kHwGlGpuTimeBottomToBottomEndIndexGfx7;       ///< Index of time of the current command reaching bottom of pipe for Gl for Gfx7 family
    extern const unsigned int                                kHwGlGpuTimeTopToBottomDurationIndexGfx7;     ///< Index of execution duration of the current command from top of pipe to bottom of pipe, may include overhead of time in queue for Gl for Gfx7 family
    extern const unsigned int                                kHwGlGpuTimeTopToBottomStartIndexGfx7;        ///< Index of time that the current command reaches the top of pipe for Gl for Gfx7 family
    extern const unsigned int                                kHwGlGpuTimeTopToBottomEndIndexGfx7;          ///< Index of time that the current command reaches the bottom of pipe for Gl for Gfx7 family
    extern const std::set<unsigned int>                      kHwGlTimestampBlockIdsGfx7;                   ///< Timestamp block id's for Gl for Gfx7 family
    extern const std::set<unsigned int>                      kHwGlTimeCounterIndicesGfx7;                  ///< Timestamp counter indices for Gl for Gfx7 family
    extern const unsigned int                                kHwGlGroupCountGfx7;                          ///< Hardware Group Count for Gl for Gfx7 family
    extern const unsigned int                                kGlPaddedCounterGroupCountGfx7;               ///< reserved counter group count for Gl for Gfx7 family
    extern const unsigned int                                kHwGlSqGroupCountGfx7;                        ///< Hardware SQ Group Count for Gl for Gfx7 family
    extern const unsigned int                                kHwGlSqIsolatedGroupCountGfx7;                ///< Hardware Isolated Group Count for Gl for Gfx7 family

    /// @brief If the requested ASIC type is supported, then the global GPU generation block instance counters are updated.
    ///
    /// @param [in] asic_type The ASIC type that is currently in use.
    ///
    /// @return True if the ASIC is matched by this file and block instances are updated, otherwise false.
    inline bool OverrideMaxBlockEvents(GDT_HW_ASIC_TYPE asic_type)
    {
        UNREFERENCED_PARAMETER(asic_type);

        return true;
    }
}  //  namespace counter_gl_gfx7

// clang-format on

#endif  // GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GL_GFX7_H_
