//==============================================================================
// Copyright (c) 2010-2023 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX7.
//==============================================================================

// This file is NOT autogenerated by the ConvertHWEnums project.

#ifndef GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX7_H_
#define GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX7_H_

// clang-format off

#include <vector>

struct GpaHardwareCounterDesc;


namespace counter_gfx7
{
    extern std::vector<GpaHardwareCounterDesc> CB0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB4countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB5countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB6countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB7countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB8countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB9countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB10countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB11countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB12countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB13countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB14countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> CB15countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB4countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB5countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB6countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB7countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB8countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB9countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB10countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB11countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB12countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB13countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB14countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> DB15countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> GRBMcountersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SU0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SU1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SU2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SU3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SC0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SC1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SC2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> PA_SC3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SX0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SX1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SX2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SX3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SPI0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SPI1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SPI2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SPI3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_ES0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_ES1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_ES2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_ES3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_GS0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_GS1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_GS2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_GS3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_VS0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_VS1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_VS2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_VS3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_PS0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_PS1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_PS2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_PS3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_LS0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_LS1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_LS2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_LS3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_HS0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_HS1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_HS2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_HS3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_CS0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_CS1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_CS2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> SQ_CS3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA4countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA5countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA6countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA7countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA8countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA9countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA10countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA11countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA12countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA13countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA14countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA15countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA16countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA17countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA18countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA19countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA20countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA21countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA22countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA23countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA24countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA25countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA26countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA27countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA28countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA29countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA30countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA31countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA32countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA33countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA34countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA35countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA36countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA37countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA38countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA39countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA40countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA41countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA42countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TA43countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP4countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP5countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP6countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP7countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP8countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP9countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP10countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP11countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP12countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP13countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP14countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP15countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP16countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP17countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP18countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP19countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP20countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP21countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP22countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP23countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP24countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP25countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP26countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP27countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP28countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP29countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP30countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP31countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP32countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP33countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP34countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP35countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP36countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP37countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP38countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP39countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP40countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP41countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP42countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCP43countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC4countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC5countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC6countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC7countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC8countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC9countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC10countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC11countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC12countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC13countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC14countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> TCC15countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> VGT0countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> VGT1countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> VGT2countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> VGT3countersGfx7;
    extern std::vector<GpaHardwareCounterDesc> GPUTimecountersGfx7;
} // counter_gfx7

// clang-format on

#endif  // GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX7_H_
