//==============================================================================
// Copyright (c) 2010-2023 Advanced Micro Devices, Inc. All rights reserved.
/// @author AMD Developer Tools Team
/// @file
/// @brief Hardware counter info for GFX6.
//==============================================================================

// This file is NOT autogenerated by the ConvertHWEnums project.

#ifndef GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX6_H_
#define GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX6_H_

// clang-format off

#include <vector>

struct GpaHardwareCounterDesc;


namespace counter_gfx6
{
    extern std::vector<GpaHardwareCounterDesc> CB0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> CB1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> CB2countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> CB3countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> CB4countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> CB5countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> CB6countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> CB7countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB2countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB3countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB4countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB5countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB6countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> DB7countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> GRBMcountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> PA_SU0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> PA_SU1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> PA_SC0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> PA_SC1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SX0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SX1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SX2countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SX3countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SPI0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SPI1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA2countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA3countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA4countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA5countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA6countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA7countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA8countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA9countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA10countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA11countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA12countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA13countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA14countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA15countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA16countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA17countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA18countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA19countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA20countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA21countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA22countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA23countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA24countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA25countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA26countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA27countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA28countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA29countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA30countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TA31countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP2countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP3countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP4countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP5countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP6countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP7countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP8countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP9countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP10countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP11countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP12countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP13countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP14countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP15countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP16countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP17countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP18countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP19countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP20countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP21countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP22countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP23countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP24countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP25countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP26countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP27countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP28countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP29countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP30countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCP31countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC2countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC3countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC4countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC5countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC6countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC7countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC8countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC9countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC10countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> TCC11countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> VGT0countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> VGT1countersGfx6;
    extern std::vector<GpaHardwareCounterDesc> GPUTimecountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ_HScountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ_PScountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ_VScountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ_GScountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ_EScountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ_CScountersGfx6;
    extern std::vector<GpaHardwareCounterDesc> SQ_LScountersGfx6;
} // counter_gfx6

// clang-format on

#endif  // GPA_AUTO_GENERATED_GPU_PERF_API_COUNTER_GENERATOR_GPA_HW_COUNTER_GFX6_H_
